modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "flight_tracking"
version = "${version}"
displayName = "FlightTracking"
authors = "ajh123"
description = '''
Flight Tracking for Minecraft
'''
#logoFile = ""

[[dependencies.flight_tracking]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flight_tracking]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flight_tracking]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "flight_tracking.mixins.json"
